#!/usr/bin/env python3
"""Stamp measured metrics from results.json into the Obsidian vault.

Enforces the project rule: **CER values are never hand-typed into vault notes.**
They are written here, sourced from results.json (the test_baseline.py artifact),
into marked auto-generated regions of the vault's INDEX.md and project/status.md.

Usage:
    python scripts/sync_vault.py          # stamp from the existing results.json
    python scripts/sync_vault.py --run    # run test_baseline.py first, then stamp

The vault is gitignored and may not exist on a fresh clone; this script exits
cleanly (status 0) in that case so it is safe to wire into a Makefile target.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results.json"
VAULT = ROOT / "maltese-vault"
TARGETS = [VAULT / "INDEX.md", VAULT / "project" / "status.md"]

BEGIN = "<!-- CER:BEGIN (auto-generated by scripts/sync_vault.py — do not edit by hand) -->"
END = "<!-- CER:END -->"


def compute() -> tuple[float, int, str]:
    """Return (average CER, image count, ISO date results.json was written)."""
    data = json.loads(RESULTS.read_text())
    cers = [entry["cer"] for entry in data]
    avg = sum(cers) / len(cers)
    measured = dt.date.fromtimestamp(RESULTS.stat().st_mtime).isoformat()
    return avg, len(cers), measured


def render_block(avg: float, count: int, measured: str) -> str:
    return (
        f"{BEGIN}\n"
        f"**Measured CER: {avg:.4f}** · {count} dev-set images · "
        f"from `results.json` ({measured})\n"
        f"{END}"
    )


def stamp(path: Path, block: str, avg: float, measured: str) -> bool:
    """Replace the marked CER region and refresh any frontmatter keys present."""
    text = path.read_text()

    if BEGIN not in text or END not in text:
        print(f"  ! {path.relative_to(ROOT)}: missing CER markers, skipped", file=sys.stderr)
        return False

    text = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S
    )
    # Only rewrites keys that already exist — no-op where they don't.
    text = re.sub(r"(?m)^cer_current:.*$", f"cer_current: {avg:.4f}", text)
    text = re.sub(r"(?m)^cer_measured:.*$", f"cer_measured: {measured}", text)

    path.write_text(text)
    print(f"  ✓ {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--run",
        action="store_true",
        help="run test_baseline.py before stamping (regenerates results.json)",
    )
    args = parser.parse_args()

    if not VAULT.exists():
        print(f"Vault not found at {VAULT} — nothing to sync (this is fine).")
        return 0

    if args.run:
        print("Running test_baseline.py …")
        subprocess.run([sys.executable, "test_baseline.py"], cwd=ROOT, check=True)

    if not RESULTS.exists():
        print(
            f"No {RESULTS.name} found. Run `python test_baseline.py` "
            f"(or pass --run) first.",
            file=sys.stderr,
        )
        return 1

    avg, count, measured = compute()
    block = render_block(avg, count, measured)
    print(f"Stamping CER {avg:.4f} ({count} images, measured {measured}):")
    for target in TARGETS:
        if target.exists():
            stamp(target, block, avg, measured)
        else:
            print(f"  - {target.relative_to(ROOT)}: not present, skipped")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
